[build-system]
requires = [ "setuptools",]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.9"
name = "iris_kedro"
readme = "README.md"
dynamic = [ "version",]
dependencies = [ "ipython>=8.10", "jupyterlab>=3.0", "notebook", "kedro~=0.19.15",]

[project.scripts]
iris-kedro = "iris_kedro.__main__:main"

[tool.kedro]
package_name = "iris_kedro"
project_name = "iris-kedro"
kedro_init_version = "0.19.15"
tools = "['None']"
example_pipeline = "False"
source_dir = "src"

[project.entry-points."kedro.hooks"]

[tool.setuptools.dynamic.version]
attr = "iris_kedro.__version__"

[tool.setuptools.packages.find]
where = [ "src",]
namespaces = false
